"""empty message

Revision ID: 08fc501cb6ce
Revises: 65552a43698a
Create Date: 2025-07-10 22:31:32.799040

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "08fc501cb6ce"
down_revision: Union[str, None] = "65552a43698a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("schools", sa.Column("grade_system", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("schools", "grade_system")
    # ### end Alembic commands ###
