"""empty message

Revision ID: 1d6edbba61c5
Revises: 8364760b8032
Create Date: 2025-07-17 00:57:36.826304

"""

from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = "1d6edbba61c5"
down_revision: Union[str, None] = "8364760b8032"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
