"""empty message

Revision ID: 5676d9898355
Revises: ef627eb422a2
Create Date: 2025-07-10 23:02:02.500880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5676d9898355'
down_revision: Union[str, None] = 'ef627eb422a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uniqueconst_schedule_student', 'grades', ['schedule_id', 'student_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uniqueconst_schedule_student', 'grades', type_='unique')
    # ### end Alembic commands ###
