"""empty message

Revision ID: 61d0773b37cc
Revises: db1b92e3f679
Create Date: 2025-07-09 21:21:20.202463

"""

from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = "61d0773b37cc"
down_revision: Union[str, None] = "db1b92e3f679"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
