"""empty message

Revision ID: 8a539dfbeaad
Revises: 08fc501cb6ce
Create Date: 2025-07-10 22:32:51.154255

"""

from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = "8a539dfbeaad"
down_revision: Union[str, None] = "08fc501cb6ce"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
