"""empty message

Revision ID: 983390d9997e
Revises: 254c07d33ebc
Create Date: 2025-06-27 21:00:52.034514

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "983390d9997e"
down_revision: Union[str, None] = "254c07d33ebc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
