"""empty message

Revision ID: 9da624a416b3
Revises: cf520ea40ee2
Create Date: 2025-06-30 14:23:34.697904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9da624a416b3'
down_revision: Union[str, None] = 'cf520ea40ee2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('homeworks', sa.Column('subject_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'homeworks', 'subjects', ['subject_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'homeworks', type_='foreignkey')
    op.drop_column('homeworks', 'subject_id')
    # ### end Alembic commands ###
