"""empty message

Revision ID: a7f10b0fdc18
Revises: 17751f06c259
Create Date: 2025-05-30 17:50:49.706718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7f10b0fdc18'
down_revision: Union[str, None] = '17751f06c259'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('users_hashed_password_key'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('users_hashed_password_key'), 'users', ['hashed_password'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
