"""empty message

Revision ID: b16a14d9e28e
Revises: 5676d9898355
Create Date: 2025-07-16 20:44:18.465681

"""

from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = "b16a14d9e28e"
down_revision: Union[str, None] = "5676d9898355"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
