"""empty message

Revision ID: c265b6276f3d
Revises: 1ecf66fe96cf
Create Date: 2025-07-04 00:57:37.980293

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c265b6276f3d"
down_revision: Union[str, None] = "1ecf66fe96cf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "attendances", "marked_by", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "attendances", "marked_by", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###
