"""empty message

Revision ID: d376e64439de
Revises: 8a539dfbeaad
Create Date: 2025-07-10 22:33:43.635911

"""

from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = "d376e64439de"
down_revision: Union[str, None] = "8a539dfbeaad"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
