"""empty message

Revision ID: db1b92e3f679
Revises: 9d533281f999
Create Date: 2025-07-09 19:02:22.942779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db1b92e3f679'
down_revision: Union[str, None] = '9d533281f999'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attendances', 'status',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attendances', 'status',
               existing_type=sa.String(),
               type_=sa.BOOLEAN(),
               existing_nullable=False)
    # ### end Alembic commands ###
