"""empty message

Revision ID: e87e708f110b
Revises: 48fa5475cd41
Create Date: 2025-07-29 22:29:07.630903

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "e87e708f110b"
down_revision: Union[str, None] = "48fa5475cd41"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
